### ISSUE TITLE
Text data type

### ISSUE THREAD

**Issue by Maclay74** [jchristn/WatsonORM#11]
Hey, I'm trying to wrap my head around the library, it looks great!

I might be wrong, but how do we store long text in database? "Text" is one of the basics data types, how is it not implemented?.. 

Thanks.

**Comment by jchristn** [comment]
Hi and thanks for the kind words. For the front end, use nvarchar and specify a length. The library is designed to provide commonality across different database types. Some database types permit a text designation with no length property and others don't. Since the library allows you to abstract the database it has to work with the least common denominator. Cheers
