### ISSUE TITLE
WatsonORM.MySQL INSERT returns null if there are multiple primary keys

### ISSUE THREAD

**Issue by DegenerateFinance** [jchristn/WatsonORM#13]
Sorry it's my first issue. Feedback about clarity and structure will be appreciated

My table structure
![image](https://github.com/jchristn/WatsonORM/assets/99656267/3ee9bbbc-3290-4985-9495-60e35be4d4f5)

My code
![image](https://github.com/jchristn/WatsonORM/assets/99656267/c097d8c3-7049-4d3f-a3b7-36514d6b8314)

Debug statement
![image](https://github.com/jchristn/WatsonORM/assets/99656267/e977a652-73f9-40bf-950e-d385bacda566)

The row still gets inserted in the table

**Comment by jchristn** [comment]
Hi @DegenerateFinance one of the limitations of the library is that it expects a single primary key per table.  If you'd like to modify and submit a PR that works across the various supported databases, I'd love to take it.  Otherwise at this point I don't have an active backlog to improve this library, only for bugfixes.  Cheers

**Comment by DegenerateFinance** [comment]
Thank you for your response. I'm right now trying to meet a deadline and even committed sacrilege by hardcoding DataTableToObjectList as public. Hopefully after the deadline I have some time and enough level of understanding to be able to contribute.
