### ISSUE TITLE
SQLite and WITHOUT ROWID

### ISSUE THREAD

**Issue by bukkideme** [jchristn/WatsonORM#3]
Hi!

Is it possible to make an SQLite table "WITHOUT ROWID" (https://www.sqlite.org/withoutrowid.html)?
Thanks,
Best Regards!

**Comment by jchristn** [comment]
Hi @bukkideme thanks for your note.  Since it isn't a capability that is consistent across DBMS, it's not something I would want to build into the library.  But please feel free to clone and modify as you see fit!

![image](https://user-images.githubusercontent.com/1421081/128880068-0c38114e-ce4b-412d-87d3-0e6c0edf0088.png)
